### ISSUE TITLE
Namespace redefinition in a child doesn’t generate a new xmlns “attribute”

### ISSUE THREAD

**Issue by linkmauve** [netvl/xml-rs#112]
When an element defines another namespace for the same prefix, for example `<a xmlns="a"><b xmlns="b"/></a>`, the inner element gets its `xmlns` “attribute” skipped, leading to a wrong document.

Here is a minimal example reproducing this issue: http://linkmauve.fr/files/xml.rs

**Comment by netvl** [comment]
Thanks, this is serious. Will fix soon.

**Comment by netvl** [comment]
@linkmauve, I've fixed this in 0.2.4.

**Comment by netvl** [comment]
Sorry, I've yanked 0.2.4 because it contains #109 which is a breaking change. Please use 0.3 version instead.
