### ISSUE TITLE
Failing to build on ARM

### ISSUE THREAD

**Issue by vinipsmaker** [netvl/xml-rs#115]
When building on ARM, I got the [following error](https://gist.github.com/vinipsmaker/5ece3172535e9d39484c):

       Compiling xml-rs v0.1.26
    error: could not exec the linker `cc`: No such file or directory (os error 2)
    Build failed, waiting for other jobs to finish...
    error: could not exec the linker `cc`: No such file or directory (os error 2)
    Could not compile `advapi32-sys`.

Then I tried latest revision on branch `master` and I got the "same" error: [error: could not exec the linker `cc`: No such file or directory (os error 2)](https://gist.github.com/vinipsmaker/162f06561f3b0aba694b).

**Comment by netvl** [comment]
Sorry, this is most definitely not xml-rs problem. You can see that [Cargo.toml](https://github.com/netvl/xml-rs/blob/master/Cargo.toml) does not contain any build script, and its only dependency is [bitflags](https://github.com/rust-lang-nursery/bitflags) which is a simple macro crate and does not have any other dependencies. Therefore, xml-rs, in terms of build process, is no different from any other library, even a simple empty one, with `bitflags` as a single dependency.

Try running `cargo build --verbose` to find the exact command which fails; I suspect there may be problems in your build setup.

**Comment by vinipsmaker** [comment]
@netvl, yes, you're right. I checked again and there was a problem with my build system. It's fixed now. Your lib compiles just fine on ARM systems.

**Comment by netvl** [comment]
@vinipsmaker just for your information, Cargo builds dependencies in parallel, so its output does not exactly corresponds to what actually happens. In particular, it doesn't mean if it stopped on some `Compiling` line that that's what failed to compile. For example, the error you provided tells that it failed to build `advapi32-sys`, not `xml-rs`.
