### ISSUE TITLE
start_element

### ISSUE THREAD

**Issue by DerGroncki** [netvl/xml-rs#116]
How to create a "start_element" from a variable that stores the "local name"?

Thanks.

Michael

**Comment by netvl** [comment]
@DerGroncki, this is a wrong place to ask such questions. Please use [Gitter chat](https://gitter.im/rust-lang/rust?utm_source=share-link&utm_medium=link&utm_campaign=share-link), IRC (although I'm almost never there, most of community chatting happens on IRC), http://users.rust-lang.org forum, [reddit](http://reddit.com/r/rust) or, most preferably, [Stackoverflow](http://stackoverflow.com/questions/tagged/rust).

As for your question, do I understand correctly that you want to write a starting element to a stream? Then you have to do something like this:
```rust
use xml::name::Name;
use xml::writer::XmlEvent;

let name = Name::prefixed("some-name", "prefix");
writer.write(XmlEvent::start_element(name));
```

If you have an `OwnedName`, you need to first obtain a `Name`, from it:
```rust
use xml::name::OwnedName;
use xml::writer::XmlEvent;

let name = OwnedName::local("whatever");
writer.write(XmlEvent::start_element(name.borrow()));
```
`OwnedName::borrow()` returns a borrowed `Name` out of an `OwnedName`.
