### ISSUE TITLE
Multiple roots should not be allowed

### ISSUE THREAD

**Issue by yblein** [netvl/xml-rs#119]
xml-rs is accepting documents with multiple root nodes while the [XML specifications says that a document must have a unique root](https://www.w3.org/TR/xml/#NT-document).

For instance, the following program

``` rust
extern crate xml;
use xml::reader::{EventReader, XmlEvent};

fn main() {
    for e in EventReader::new(&b"<a/><a/>"[..]) {
        match e {
            Ok(XmlEvent::StartElement { name, .. }) => {
                println!("start: {}", name);
            }
            Err(e) => {
                println!("error: {}", e);
                break;
            }
            _ => {}
        }
    }
}
```

will print

```
start: a
start: a
```

instead of an error.

The issue exists both in `0.3` and `master`.

**Comment by netvl** [comment]
Thanks, this is bad indeed. I was sure that this case was handled.

**Comment by l1048576** [comment]
`EventReader` can be used to read partial XML (such as [DocumentFragment](https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment)?).
I think it is better that handling of multiple root nodes can be controllable by `ParserConfig`, rather than treat it as error always.
