### ISSUE TITLE
Rename crate from 'xml-rs' to 'xml'

### ISSUE THREAD

**Issue by dtolnay** [netvl/xml-rs#129]
Every crate on crates.io is for Rust :smile: no reason for the -rs suffix.

**Comment by netvl** [comment]
I may rename it when I release the next large version. But still, there are many crates with `-rs` suffix out there :)

**Comment by RReverser** [comment]
@netvl I'm surprised Cargo itself didn't strip the suffix for you as it does nowadays for any new project.

**Comment by vi** [comment]
Now it has stopped doing that.

**Comment by kornelski** [comment]
The `xml` crate is owned by @Plecra

**Comment by kornelski** [comment]
Done! 🎉
