### ISSUE TITLE
References in text are trimmed as whitespaces

### ISSUE THREAD

**Issue by RReverser** [netvl/xml-rs#140]
Example:

```xml
<bla>&#9835;</bla>
```

I tracked this to https://github.com/netvl/xml-rs/blob/master/src/reader/parser/outside_tag.rs#L66 and there `inside_whitespace` says `true` even though it's not a whitespace, so character is trimmed.

If I have any letter before the reference like

```xml
<bla>x&#9835;</bla>
```

then `inside_whitespace` is properly set to `false` and I see output.

**Comment by netvl** [comment]
Hm, good catch, I'll look into it, thanks!

**Comment by netvl** [comment]
Fixed this in the 0.3.7 version, already on crates.io.

**Comment by netvl** [comment]
0.3.7 contained a problem introduced by the fix, so I've yanked it. 0.3.8 should be okay.
