### ISSUE TITLE
Backwards incompatible 0.3.7 - 0.3.8 versions

### ISSUE THREAD

**Issue by Razican** [netvl/xml-rs#141]
Since the additions to the `ParserConfig` struct, new versions are no longer backwards compatible, even though the only change in the version number was the patch number. This is making projects to stop building.

**Comment by netvl** [comment]
I'm sorry :( Somehow it didn't occur to me that it is a backwards-incompatible change. Indeed, this is bad. I'll yank offending versions and publish a `0.4.0` instead.

**Comment by netvl** [comment]
Done. 0.3.7 and 0.3.8 are now yanked, and 0.4.0 is published with changes from 0.3.7 and 0.3.8. Sorry again!
