### ISSUE TITLE
Multiple codepoints needed for `ParserConfig::add_entity`

### ISSUE THREAD

**Issue by gjtorikian** [netvl/xml-rs#149]
First, thanks for this great project.

Second, thanks to you and @danigm for adding https://github.com/netvl/xml-rs/pull/139.

Third: my use-case follows @danigm's (I'm parsing some XHTML files with zany entities), and unfortunately, the char bytesize is not enough to hold some HTML entities.

For example, when trying to add [`&NotEqualTilde;`](http://reference.wolfram.com/language/ref/character/NotEqualTilde.html) (≂̸), the compiler (rightly) complains with

```
error: character literal may only contain one codepoint: '≂
```

(For reference, a _full_ list of HTML5 entities can be found [here](https://github.com/kivikakk/comrak/blob/6e59dec010ffba85ed3afa9c18404a3d92b4606d/src/entity_data.rs); I'm using the same script/list.)

I'm interested in making a patch, but I am not sure how to go about it. I could make [a change here](https://github.com/netvl/xml-rs/blob/02eea9384cce3666fadc13cce1111824db25b322/src/reader/parser/inside_reference.rs#L22) to include the same list of HTML5 entity data, as seen in the `comrak` project above. This would require accepting strings instead of chars for `add_entity`, too. 

Does that make sense? Is there a better way to add support for this?

**Comment by gjtorikian** [comment]
https://github.com/p-jackson/entities may also be an incredibly easy way to do this.

**Comment by danigm** [comment]
I've just made a pull request that solves this: https://github.com/netvl/xml-rs/pull/150

**Comment by netvl** [comment]
Yes, this is indeed a bug; it follows from the XML spec that entities may result into arbitrary strings.
