### ISSUE TITLE
Invalid XML input is parsed as valid

### ISSUE THREAD

**Issue by linkmauve** [netvl/xml-rs#152]
While I was fuzzing my [XMPP parser](https://hg.linkmauve.fr/xmpp-parsers), I found an invalid sample:
```xml
<message xmlns=invalid "jabber:client"/>
```

This is parsed the same way as this valid sample:
```xml
<message xmlns="jabber:client"/>
```

It would be useful for you to fuzz your library as well, to make sure that kind of issue doesn’t happen in the future.

**Comment by netvl** [comment]
Thanks! Actually, fuzzing did find some bugs in xml-rs, so this is a thing I probably would like to add, but unfortunately I don't have much time lately :(

**Comment by kornelski** [comment]
Fixed in https://github.com/kornelski/xml-rs/commit/9b99b03
