### ISSUE TITLE
Yank 0.6.2

### ISSUE THREAD

**Issue by jethrogb** [netvl/xml-rs#158]
Please yank 0.6.2. It bumps the minimum required version of rustc to 1.20 because of the bitflags 1.0 dependency. Minor version increases should not change compiler version requirements.

**Comment by netvl** [comment]
Sorry, I was not aware of that. I will release 0.7.0 instead.

**Comment by netvl** [comment]
Done, 0.6.2 is yanked, 0.7.0 is released.
