### ISSUE TITLE
Should users update to v0.7?

### ISSUE THREAD

**Issue by chetgurevitch** [netvl/xml-rs#160]
I saw that bb39eee35b6a861d6a9c0a50dda6152a222e4a76 removes the bitflags dependency completely, so I was wondering if projects should update to v0.7 or if it'll be yanked in favor of continuing 0.6.

**Comment by netvl** [comment]
@chetgurevitch sorry for the late response. I'm not sure I understand your question. I don't plan to yank any versions right now; it's just the next version (likely 0.8.0) will no longer have a dependency on bitflags.

**Comment by chetgurevitch** [comment]
Cool, thanks.
