### ISSUE TITLE
Access content inside xml node

### ISSUE THREAD

**Issue by xhallix** [netvl/xml-rs#162]
Maybe not an issue - but I'm not able to find it in the documentation.
How can I get the text inside the xml node like `<foo> bar </foo>` ?

**Comment by netvl** [comment]
Hello @xhallix, sorry for the late response. You get the text inside an XML node by parsing further - if you get a `StartElement` event, then the series of events until the `EndElement` event will designate your text between the opening and closing tags.

**Comment by xhallix** [comment]
@netvl thanks for the reply 👍  I just closed it because I saw I can also parse character. 
thanks for you great crate btw - it's very nice to use!
