### ISSUE TITLE
Link to https://github.com/RazrFalcon/choose-your-xml-rs

### ISSUE THREAD

**Issue by jrmuizel** [netvl/xml-rs#166]
It would be valuable for people looking for xml library to see what alternatives are out there. choose-your-xml-rs seems like the best place to do this right now.

**Comment by netvl** [comment]
This is good thing to do, I agree. If you want, you can send a PR which adds a link to that page to the readme file.

**Comment by kornelski** [comment]
That page doesn't exist any more
