### ISSUE TITLE
EventWriter::flush()

### ISSUE THREAD

**Issue by dvtomas** [netvl/xml-rs#167]
It would be handy if `EventWriter` implemented a `flush()` method, that would just flush the underlying sink.

My use-case is a long-running measurement application that occasionally saves a complex XML element into a file backed by a `BufWriter`. I'd like to flush the writer each time I save a new element so I have the relevant info stored in case of failure.

**Comment by dvtomas** [comment]
Sure, that would work for me..

**Comment by netvl** [comment]
Yes, I think adding `inner()` would be a more generic approach. I agree that it could make emitting invalid XML possible, but it is anyway possible now, because the emitter does not do escaping in some cases. I'll add such a method now.

**Comment by netvl** [comment]
`inner_mut()` is now available in 0.8.0, which is released to crates.io. I guess this could be closed. Sorry for the delay!

**Comment by netvl** [comment]
https://docs.rs/xml-rs/0.8.0/xml/writer/struct.EventWriter.html#method.inner_mut

**Comment by dvtomas** [comment]
Great, thank you so much.
