### ISSUE TITLE
";<?" breaks StartDocument guarantees and is treated as normal XML

### ISSUE THREAD

**Issue by Kampfkarren** [netvl/xml-rs#177]
As documented here:

![image](https://user-images.githubusercontent.com/3190756/61062145-81480e00-a3b2-11e9-9082-352fb69be185.png)

StartDocument must always be the first event emitted. However, this code:

```
    println!(
        "{:?}",
        xml::EventReader::from_str(";<?")
            .next()
    );
```

Prints: `Ok(Characters(;))`

**Comment by kornelski** [comment]
Fixed
