### ISSUE TITLE
Catch empty tag

### ISSUE THREAD

**Issue by rusnasonov** [netvl/xml-rs#181]
Is the way to catch empty tag? I have XML like this
```
<a></a>
<a>
  <b>some text</b>
</a>
```
And I want to known where `a` tag is empty. I  counted that empty tag emmit Characters event with empty data, but it's not.

**Comment by kornelski** [comment]
When you get StartElement start counting Characters or Whitespace events (they are never empty), and when you get EndElement you will know if there were any.
