### ISSUE TITLE
Parsing fails on surrogate pair entity references

### ISSUE THREAD

**Issue by bryanburgers** [netvl/xml-rs#187]
I recently ported a library from Go to Rust, using xml-rs. It was working wonderfully.

This morning, the Go library continued to work but the Rust library started returning invalid XML results.

Reducing the issue, it is because the standard Go XML parser in its standard configuration is able to parse the following reduced XML document, but xml-rs is not.

```xml
<doc>&#xd83d;&#xdd34;</doc>
```

You might recognize those values as coming from unicode's surrogate pair range. I suspect that the up-stream process that I'm unable to control is serializing UTF-16 bytes into a UTF-8 XML document using character entity references.

The Go XML parser replaces both characters with [REPLACEMENT CHARACTER (U+FFFD)](https://www.fileformat.info/info/unicode/char/fffd/index.htm) instead of marking the document as invalid. I believe that _technically_ this is the incorrect behavior according to the spec, but _practically_ it is extremely useful to the end user.

It would be incredibly helpful if xml-rs would follow the same precedent when encountering entity references that cannot be mapped directly to Rust's `char`.

I see two potential courses of action.

The **first potential course of action** is that xml-rs *always* follows the Go XML parser's precedent and always maps these entity references to U+FFFD. The advantage is that this will _just work_ for documents that contain these entity references while not affecting any other documents. The disadvantage is that, _per spec_, xml-rs would be accepting an XML document that is technically invalid. But as I said earlier, _practically_, this is extremely useful behavior to the end user. (#188)

The **second potential course of action** is to add an option to ParserConfig that allows this conversion when set. The advantage is that users would opt-in to using a technically non-spec-compliant XML parser. The disadvantage is that users rarely know they need to set this option until they find out in production that they need to set this option. (#189)

---

Rust reproduction:

```rust
fn main() {
    let input = "<doc>&#xd83d;&#xdd34;</doc>";
    let reader = xml::EventReader::new(input.as_bytes());

    for event in reader {
        println!("{:?}", event);
    }
}
```

Rust output:

```
Ok(StartDocument(1.0, UTF-8, None))
Ok(StartElement(doc, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"}))
Err(Error { pos: 1:13, kind: Syntax("Invalid hexadecimal character number in an entity: #xd83d") })
```

---

Go reproduction:

```go
package main

import "fmt"
import "strings"
import "encoding/xml"

func main() {
    s := "<doc>&#xd83d;&#xdd34;</doc>"
    read := strings.NewReader(s)
    decoder := xml.NewDecoder(read)
    for {
        token, err := decoder.Token()
        if err != nil {
            fmt.Println(err)
            break
        } else {
            c, ok := token.(xml.CharData)
            if ok {
                s := string(c)
                for index, runeValue := range s {
                    fmt.Printf("%#U starts at byte position %d\n", runeValue, index)
                }
            }
        }
    }
}
```

Go output:

```
U+FFFD '�' starts at byte position 0
U+FFFD '�' starts at byte position 3
EOF
```

**Comment by netvl** [comment]
Thank you very much for the thorough report and two (!) pull requests!

The primary idea of the xml-rs crate is that it tries to be as close to the XML standard as possible. This means that behavior like this should be optional/configurable. I do agree that it might be useful to have, anyway.

**Comment by bryanburgers** [comment]
Glad to do it! And two pull requests wasn't a big deal (they were quite similar). I figured if I made it as easy on you as possible, it would increase the chances that one of them gets accepted!
