### ISSUE TITLE
Performance compared to VTD XML ?

### ISSUE THREAD

**Issue by stuaxo** [netvl/xml-rs#199]
Hi,
   I'm having trouble working out the performance of dfferent XML libraries.
VTD XML says on a "Core2 2.5Ghz Desktop, VTD-XML outperforms DOM parsers by 5x~12x, delivering 150~250 MB/sec per core sustained throughput."

But I can't really compare that to xml-rs, any idea how they compare ?

**Comment by kornelski** [comment]
Unfortunately I can't provide a comparable number, because I don't have a machine with this CPU, plus performance highly depends on the complexity of the XML file being parsed.

I expect xml-rs to be fast enough for most purposes, but it won't win benchmarks against parsers written for speed.
