### ISSUE TITLE
Maintenance of xml-rs

### ISSUE THREAD

**Issue by kornelski** [netvl/xml-rs#221]
I'd like to help with the maintenance of this crate.

**Comment by netvl** [comment]
I will start a process of approval to do anything with this project with my employer. Unfortunately, it will take some time - last time it took about 2.5-3 months. After this is done, I will be able to transfer ownership/add maintainers/etc.

**Comment by untereiner** [comment]
Hi! Any news on this ?

**Comment by mgeisler** [comment]
Hi @netvl, I would also like to help here, if needed. I work on Android as part of the team which supports Rust in Android. We use [the crate in an Android component related to virtualization](https://cs.android.com/android/platform/superproject/+/master:packages/modules/Virtualization/virtualizationservice/). So we'll like to help with the maintenance :smiley:

**Comment by netvl** [comment]
Hi @kornelski  @untereiner @mgeisler 
I really appreciate your suggestions to take over maintenance of this crate!
I’m sorry for the radio silence - I can only say that I did request an approval for project transfer some time ago, but unfortunately I can’t tell how long it would take to be fully processed. From my experience, this timing is inconsistent, and may be further delayed by holidays. I will update this ticket immediately once I get the approval.

**Comment by netvl** [comment]
Hi everyone,

I have good news - I have just received an approval to go through with the maintenance transfer. I can do the necessary work any time. That being said, I'm not sure who I can transfer the crate to. Those who volunteered, is it all right for me to ask you to confirm your intention here? I personally don't really have a specific preference, but if you have experience with crate maintenance/have some crates that you actively maintain, that would be the best. Thank you!

**Comment by hoijui** [comment]
niiiice! :-)
I would prefer not to be in charge. I would vote for one person being in charge, but one or two more to also have owner rights (also: probably not me). I would do the later, in case something simple needs be done quick, and the main person is on holidays or goes missing due to personal issues in life.

**Comment by kornelski** [comment]
I'm still interested.

**Comment by netvl** [comment]
Big thanks for @kornelski to taking over the maintenance!
@kornelski have you switched everything to the new repo? Do you think it would make sense to archive this one? I wanted to suggest to transfer the repository to keep the issue/PR history as well, but if you think that it is unnecessary it is also fine, I guess)

**Comment by kornelski** [comment]
It would be nice if you could transfer the repo, or at least give me access so that I can close issues.
