### ISSUE TITLE
Simple way to remove whitespaces

### ISSUE THREAD

**Issue by igiona** [netvl/xml-rs#230]
I'm looking for a simple way to remove all the unnecessary whitespaces from a "human readable" XML string, to reduce the XML-size for machine-to-machine communication.
```xml
<my>
   <beautiful>XML</beautiful>
</my>
```
should result in:
```xml
<my><beautiful>XML</beautiful></my>
```

In there already something available in this library?

**Comment by kornelski** [comment]
There's a `trim_whitespace()` config option. See also document rewriting example https://github.com/netvl/xml-rs/blob/master/examples/rewrite.rs
