### ISSUE TITLE
Deal with files that start with empty line 

### ISSUE THREAD

**Issue by patrickelectric** [netvl/xml-rs#231]
Is there a way to handle files that start with empty lines ?

Like
```
// Empty line
<?xml version="1.0" encoding="UTF-8"?>
;;;
```

**Comment by kornelski** [comment]
The XML spec is unfortunately quite pedantic about it, and requires these files to be rejected.

You need to trim the whitespace before parsing. If you have the source as a string, it's enough to call `trim_start()`.

If you use `io::Read`, then wrap it in `BufReader`, fill the buf, check how many whitespace bytes are there, and call `.consume(n)` with that number. The hand off the bufreader to the parser.

**Comment by patrickelectric** [comment]
@kornelski thanks for the info!
