### ISSUE TITLE
Please expose a function to get the current position when parsing

### ISSUE THREAD

**Issue by Blei** [netvl/xml-rs#37]
This would be very helpful to construct error messages when figuring out where in a multi-megabyte XML monstrosity a parser goes off the tracks. It looks like it should be a relatively straightforward change too.

**Comment by gkoz** [comment]
@netvl 
So what's the plan on this? Should an event be carrying its position or should the parser provide the position of the last event?

**Comment by netvl** [comment]
@gkoz, I don't have any plans right now. I'm very sorry, but I'm very busy at my main job and I'm also working on my PhD thesis and several articles so I just physically cannot work on side projects now :(

As a general thought, I don't want to add additional fields to events. Either the parser should provide a method to access the current position or there should be another iterator which returns `(Event, Position)` where `Position: common::HasPosition`.

**Comment by Blei** [comment]
@gkoz Thanks a lot!
