### ISSUE TITLE
Dom Tree

### ISSUE THREAD

**Issue by Binero** [netvl/xml-rs#46]
This library still needs a way to construct a Document Object Model tree.

I have been experimenting with the library and looking for ways to implement it. My initial idea was to have an enumeration (`XmlObject`), similar to the `reader::events::XmlEvent` enumeration, but with the `StartDocument` and `EndDocument` events removed, and the `XmlEvent::StartElement` and `XmlEvent::EndElement` events merged into one object (`XmlObject::Element`). 

Every element-object part of a DOM tree would then contain all data that `XmlEvent::StartElement` currently contains, plus another DOM tree object. This would allow for easy inserting DOM trees inside eachother. 

A DOM tree could be as simple as an alternate type definiton for `std::vec::Vec<XmlObject>`. 

The problem with this approach is that there is a lot of redundancy, as almost everything inside `XmlEvent` would have to be redefined inside `XmlObject`. It could be better to simply make the `XmlObject` enumeration a wrapper over `XmlEvent` so that instead of every child basically storing a copy of what used to be inside the event, it contains the event. For people using the library that could however become annoying fast: you'd end up with code like: `xml_element_object.start_element_event.name.local_name` just to get the name of an XML element out of the DOM tree. 

I think we should use this issue to discuss how the DOM tree will be implemeted.

**Comment by zonyitoo** [comment]
I think the DOM structure could be

```rust
// Attribute could be represented as a Map
type OwnedAttribute = BTreeMap<OwnedName, String>;

enum XmlObject {
    Element {
        name: OwnedName,
        attributes: BtreeMap<OwnedName, String>,
        namespace: Namespace,
        children: Vec<XmlObject>,
    },
    Text(String),
}
```

**Comment by lazypenguin** [comment]
This crate provides this functionality and is built on top of xml-rs

**Comment by linkmauve** [comment]
In addition to xmltree-rs mentioned above, we now have https://crates.io/crates/minidom and https://crates.io/crates/elementtree, I’d suggest closing this issue as out of scope.

**Comment by kornelski** [comment]
I'll leave DOM construction to other crates.
