### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by oles89** [netvl/xml-rs#66]
C:\msys64\home\Alex\.cargo\registry\src\github.com-1ecc6299db9ec823\xml-rs-0.1.13\src\common.rs:67:5: 67:71 error: method `detail` is not a member of trait `error::Error`
C:\msys64\home\Alex\.cargo\registry\src\github.com-1ecc6299db9ec823\xml-rs-0.1.13\src\common.rs:67     fn detail(&self) -> Option<String> { Some(format!("{:?}", self)) }

My machine on Windows 8 64

**Comment by obsgolem** [comment]
Reproduced on `rustc 1.0.0-nightly (4874ca36f 2015-01-23 00:18:57 +0000)`.

**Comment by InfiniteDarkness** [comment]
I'm getting it, too.

**Comment by netvl** [comment]
Thanks, this is fixed in 15674ae, will be on crates.io in a few minutes.
