### ISSUE TITLE
next() -> Result<XmlEvent, Error>

### ISSUE THREAD

**Issue by gkoz** [netvl/xml-rs#82]
Have you considered making `EventReader::next()` return `Result<XmlEvent, Error>` and removing the `Error` variant? It seems this could make bubbling up errors from recursive handlers a lot easier (with `try!`).

**Comment by netvl** [comment]
When I started writing the library, there were no conventions and best practices on this. For example, `lines()` iterator returned just `String`.
Now, however, it seems that returning `Result` from an iterator *is* the best practice for such things, so yes, it probably does make sense to change it.

**Comment by netvl** [comment]
Implemented this in 0.2.0, `EventReader::next()` now returns `Result<XmlEvent>` where `type Result<T> = result::Result<T, Error>`.
