### ISSUE TITLE
very slow

### ISSUE THREAD

**Issue by s-trooper** [netvl/xml-rs#99]
i took the usage example from the project main page and apply it to my 3 MB xml file with this result:

python: 00.968 sec (CPython/xml.etree, i have Java parser that are ~10x faster that this one)
rust:      04.310 sec (without prints traversing only!)

- Win7 64 x
- cargo build --release (rust 1.1)

**Comment by xitep** [comment]
Can you post your code? How are you reading the file?

**Comment by s-trooper** [comment]
just like example
```rust
let file = File::open(&filename).unwrap();
let start = PreciseTime::now();
let mut parser = EventReader::new(file);

for e in parser.events() {
    match e {
        XmlEvent::StartElement { name, .. } => {
        }
        XmlEvent::EndElement { name } => {
        }
        XmlEvent::Error(e) => {
            println!("Error: {}", e);
            break;
        }
        _ => {}
    }
}
let end = PreciseTime::now();
println!("{} seconds for whatever you did.", start.to(end));
```

**Comment by xitep** [comment]
Can you try wrapping `file` with `BufReader`? https://doc.rust-lang.org/stable/std/io/struct.BufReader.html

Something along the lines:

```
let file = File::open(...)...
let file = BufReader::new(file)...
...
```

I'd be interested how much this helps.

**Comment by netvl** [comment]
Yes, the example on the main page was written when `File` was a buffered reader itself, it was long time ago. I didn't update it for `BufReader` since. Because xml-rs essentially processes the input code point-wise, it is very likely that absence of buffering *is* the bottleneck.

If `BufReader` won't help, could you please post the XML document you're working with? I'll try to look what's happening there.

**Comment by s-trooper** [comment]
with ```BufReader```:
rust:   00.525 sec

for me its ok the issue can be closed but as incentive:
nim:   0.049 sec (xmlparser)  :-)

**Comment by xitep** [comment]
Would you mind trying and posting the result with rust-nightly? :)

**Comment by netvl** [comment]
Yeah, I didn't optimize the parser very much, it is very likely that there are bottlenecks. I have some work on this in dev branch.

**Comment by s-trooper** [comment]
just for fun nightly: 0.475 sec. but honestly the rust compiler will not generate 10x faster binaries in near future ;-)

**Comment by xitep** [comment]
sure, i fully agree. i just was curious how much things have changes on nightly since the 1.1 release. many thanks so far.

**Comment by netvl** [comment]
I guess I'm closing this for now. Feel free to reopen if you still have problems.
